@host=http://localhost:5134

### Get All Dinners
Get {{host}}/api/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjgwZWE5OS0zYzVjLTQ3MDQtYWFkOC04ZDkxM2JjMGQ2OTIiLCJnaXZlbl9uYW1lIjoiUmFodWwiLCJmYW1pbHlfbmFtZSI6IkRleSIsImp0aSI6IjNmNDI1OGY0LTNjMjktNDlkNi1hNzZjLTMzZDRkNWU3ODgxNiIsImV4cCI6MTY5Njc1NTcxMiwiaXNzIjoiRGlubmVyIEJvb2tpbmciLCJhdWQiOiJEaW5uZXIgQm9va2luZyJ9.sYEkFF82rX4zKuy38b9qikaOuSQFC6nCZnAjhyPjjlM