@host=http://localhost:5134
@hostId=873d888c-058d-4f71-bb98-d6b24c2a244e
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEaW5uZXJCb29raW5nLkRvbWFpbi5Vc2VyQWdncmVnYXRlLlZhbHVlT2JqZWN0cy5Vc2VySWQiLCJnaXZlbl9uYW1lIjoiUmFodWwiLCJmYW1pbHlfbmFtZSI6IkRleSIsImp0aSI6IjE1OWFmYTE5LTNkMjItNGIxMS1hYWFiLWQ1NmY2MTkxZmJkNyIsImV4cCI6MTY5Njg3OTkxMSwiaXNzIjoiRGlubmVyIEJvb2tpbmciLCJhdWQiOiJEaW5uZXIgQm9va2luZyJ9.C_EJNJ4SrlXvjBdbPR8Togu_H6__1YzSeqaTWTyqu9c

### Create Menus
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Menu name",
    "description": "menu description",
    "sections":[
        {
            "name": "section name",
            "description": "section description",
            "items": [
                {
                    "name": "item name",
                    "description": "item description"
                }
            ]
        }
    ]
}